In [906]:
import numpy as np
import pandas as pd

Lee el archivo CSV y crea un DataFrame

In [926]:
temporadas = [
    '11-12',
    '12-13',
    '13-14',
    '14-15',
    '15-16',
    '16-17',
    '17-18',
    '18-19',
    '19-20',
    '20-21',
    '21-22'
]

In [927]:
numeroTemporada = temporadas[1]

In [929]:
ruta = '/content/datos_' + numeroTemporada + '.csv'

In [930]:
df = pd.read_csv(ruta)

In [931]:
df

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
0,SP1,18/08/12,Celta,Malaga,0,1,A,0,0,D,...,1.78,21,-0.25,1.99,1.96,1.98,1.91,2.35,3.45,3.29
1,SP1,18/08/12,Mallorca,Espanol,2,1,H,1,1,D,...,1.68,20,-0.50,2.01,1.98,1.95,1.90,2.25,3.33,3.63
2,SP1,18/08/12,Sevilla,Getafe,2,1,H,2,0,H,...,1.84,23,-0.75,1.90,1.82,2.12,2.05,1.68,3.96,5.73
3,SP1,19/08/12,Ath Bilbao,Betis,3,5,A,0,3,A,...,1.92,18,-0.75,2.18,2.12,1.81,1.76,2.17,3.49,3.65
4,SP1,19/08/12,Barcelona,Sociedad,5,1,H,4,1,H,...,3.36,23,-2.75,1.98,1.93,1.99,1.93,1.09,13.96,35.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,SP1,01/06/13,Mallorca,Valladolid,4,2,H,2,1,H,...,2.17,26,-1.00,1.96,1.89,2.02,1.97,1.54,4.50,6.72
376,SP1,01/06/13,Real Madrid,Osasuna,4,2,H,2,0,H,...,3.74,25,-1.50,1.71,1.68,2.33,2.24,1.26,7.25,10.85
377,SP1,01/06/13,Sevilla,Valencia,4,3,H,2,1,H,...,2.48,23,0.50,1.76,1.72,2.25,2.18,3.07,3.57,2.40
378,SP1,01/06/13,Vallecano,Ath Bilbao,2,2,D,1,1,D,...,2.35,23,-0.25,1.90,1.83,2.13,2.05,2.14,3.67,3.56
379,SP1,01/06/13,Zaragoza,Ath Madrid,1,3,A,0,0,D,...,1.98,23,-0.50,2.32,2.23,1.72,1.69,2.54,3.65,2.82

In [911]:
#df = df.assign(Season=numeroTemporada)
df.insert(0, 'Season', numeroTemporada)

In [912]:
# Crear la nueva columna "MatchID" en el DataFrame "df"
#df['MatchID'] = df.index + 1
df.insert(0, 'MatchID', df.index + 1)
# Imprimir el DataFrame actualizado
print(df)

     MatchID Season  Div        Date   Time    HomeTeam     AwayTeam  FTHG  \
0          1  19-20  SP1  16/08/2019  20:00  Ath Bilbao    Barcelona     1
1          2  19-20  SP1  17/08/2019  16:00       Celta  Real Madrid     1
2          3  19-20  SP1  17/08/2019  18:00    Valencia     Sociedad     1
3          4  19-20  SP1  17/08/2019  19:00    Mallorca        Eibar     2
4          5  19-20  SP1  17/08/2019  20:00     Leganes      Osasuna     0
..       ...    ...  ...         ...    ...         ...          ...   ...
375      376  19-20  SP1  19/07/2020  20:00     Granada   Ath Bilbao     4
376      377  19-20  SP1  19/07/2020  20:00     Leganes  Real Madrid     2
377      378  19-20  SP1  19/07/2020  20:00     Levante       Getafe     1
378      379  19-20  SP1  19/07/2020  20:00     Osasuna     Mallorca     2
379      380  19-20  SP1  19/07/2020  20:00     Sevilla     Valencia     1

     FTAG FTR  ...  AvgC<2.5  AHCh B365CAHH  B365CAHA  PCAHH  PCAHA  MaxCAHH  \
0       0   H  ...      1.97  0.75     1.93      2.00   1.91   2.01     2.02
1       3   A  ...      2.63  1.00     1.82      1.97   1.85   2.07     2.00
2       1   D  ...      1.82 -0.75     1.94      1.99   1.92   2.00     1.96
3       1   H  ...      1.66  0.00     2.11      1.82   2.09   1.83     2.12
4       1   A  ...      1.46 -0.50     1.89      2.04   1.90   2.01     1.95
..    ...  ..  ...       ...   ...      ...       ...    ...    ...      ...
375     0   H  ...      1.78 -0.75     1.96      1.97   1.93   1.98     2.04
376     2   D  ...      2.06  0.25     2.03      1.90   2.05   1.87     2.06
377     0   H  ...      2.17  1.25     1.88      2.05   1.86   2.05     1.91
378     2   D  ...      2.30 -0.75     1.85      2.08   1.85   2.07     1.89
379     0   H  ...      2.35 -0.75     1.94      1.99   1.93   1.99     1.96

     MaxCAHA  AvgCAHH  AvgCAHA
0       2.03     1.91     1.98
1       2.20     1.82     2.06
2       2.12     1.89     2.00
3       1.88     2.07     1.83
4       2.06     1.90     1.99
..       ...      ...      ...
375     1.99     1.93     1.94
376     1.93     2.00     1.88
377     2.08     1.86     2.01
378     2.11     1.84     2.04
379     2.00     1.92     1.95

[380 rows x 107 columns]

In [913]:
df

,MatchID,Season,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,1,19-20,SP1,16/08/2019,20:00,Ath Bilbao,Barcelona,1,0,H,...,1.97,0.75,1.93,2.00,1.91,2.01,2.02,2.03,1.91,1.98
1,2,19-20,SP1,17/08/2019,16:00,Celta,Real Madrid,1,3,A,...,2.63,1.00,1.82,1.97,1.85,2.07,2.00,2.20,1.82,2.06
2,3,19-20,SP1,17/08/2019,18:00,Valencia,Sociedad,1,1,D,...,1.82,-0.75,1.94,1.99,1.92,2.00,1.96,2.12,1.89,2.00
3,4,19-20,SP1,17/08/2019,19:00,Mallorca,Eibar,2,1,H,...,1.66,0.00,2.11,1.82,2.09,1.83,2.12,1.88,2.07,1.83
4,5,19-20,SP1,17/08/2019,20:00,Leganes,Osasuna,0,1,A,...,1.46,-0.50,1.89,2.04,1.90,2.01,1.95,2.06,1.90,1.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,376,19-20,SP1,19/07/2020,20:00,Granada,Ath Bilbao,4,0,H,...,1.78,-0.75,1.96,1.97,1.93,1.98,2.04,1.99,1.93,1.94
376,377,19-20,SP1,19/07/2020,20:00,Leganes,Real Madrid,2,2,D,...,2.06,0.25,2.03,1.90,2.05,1.87,2.06,1.93,2.00,1.88
377,378,19-20,SP1,19/07/2020,20:00,Levante,Getafe,1,0,H,...,2.17,1.25,1.88,2.05,1.86,2.05,1.91,2.08,1.86,2.01
378,379,19-20,SP1,19/07/2020,20:00,Osasuna,Mallorca,2,2,D,...,2.30,-0.75,1.85,2.08,1.85,2.07,1.89,2.11,1.84,2.04
379,380,19-20,SP1,19/07/2020,20:00,Sevilla,Valencia,1,0,H,...,2.35,-0.75,1.94,1.99,1.93,1.99,1.96,2.00,1.92,1.95

In [914]:
#df_transformed = pd.DataFrame(columns=['MatchID', 'Date', 'Time', 'Team', 'Goals', 'TeamLocation', 'OpposingTeam', 'FullTimeResult', 'HalfTimeResult',
  #                                     'HalfTimeGoals', 'ShotsOnTarget', 'Corners', 'FoulsCommitted', 'YellowCards', 'RedCards', 'Season'
  #                                     ])

In [915]:
df_transformed = pd.DataFrame(columns=['MatchID', 'Date', 'Team', 'Goals', 'TeamLocation', 'OpposingTeam', 'FullTimeResult', 'HalfTimeResult',
                                     'HalfTimeGoals', 'ShotsOnTarget', 'Corners', 'FoulsCommitted', 'YellowCards', 'RedCards', 'Season'
                                     ])

In [916]:
# Recorre las filas del DataFrame
for index, row in df.iterrows():
    # Accede a los valores de cada columna en la fila actual

    match_id = index+1
    date = row['Date'] # Match Date (dd/mm/yy)
    #time = row['Time']

    home_team = row['HomeTeam'] 
    away_team = row['AwayTeam']

    fullTimeResult = row['FTR'] # Full Time Result (H=Home Win, D=Draw, A=Away Win)
    halfTimeResult = row['HTR'] # Half Time Result (H=Home Win, D=Draw, A=Away Win)

    ### (H=Home Win, D=Draw, A=Away Win) ###

    if fullTimeResult == 'H':
      fullTimeResultHome = "Victoria"
      fullTimeResultAway = "Derrota"
    elif fullTimeResult == 'D':
      fullTimeResultHome = "Empate"
      fullTimeResultAway = "Empate"
    elif fullTimeResult == 'A':
      fullTimeResultHome = "Derrota"
      fullTimeResultAway = "Victoria"
    else:
      fullTimeResultHome = "Resultado desconocido"
      fullTimeResultAway = "Resultado desconocido"

    if halfTimeResult == 'H':
      halfTimeResultHome = "Victoria"
      halfTimeResultAway = "Derrota"
    elif halfTimeResult == 'D':
      halfTimeResultHome = "Empate"
      halfTimeResultAway = "Empate"
    elif halfTimeResult == 'A':
      halfTimeResultHome = "Derrota"
      halfTimeResultAway = "Victoria"
    else:
      halfTimeResultHome = "Resultado desconocido"
      halfTimeResultAway = "Resultado desconocido"


    home_goals = row['FTHG'] # Full Time Home Team Goals
    away_goals = row['FTAG'] # Full Time Away Team Goals

    hthg = row['HTHG'] # Half Time Home Team Goals -  HalfTimeGoals
    hs = row['HS'] # Home Team Shots - Shots
    hst = row['HST'] # Home Team Shots on Target -    ShotsOnTarget
    #hhw = row['HHW'] # Home Team Hit Woodwork (El equipo local golpea la madera)
    hc = row['HC'] # Home Team Corners -              Corners
    hf = row['HF'] # Home Team Fouls Committed -      FoulsCommitted
    #hfkc = row['HFKC'] # Home Team Free Kicks Conceded-------------------------
    #ho = row['HO'] # Home Team Offsides----------------------------------------
    hy = row['HY'] # Home Team Yellow Cards -         YellowCards
    hr = row['HR'] # Home Team Red Cards -            RedCards
    #hbp = row['HBP'] # Home Team Bookings Points (10 = yellow, 25 = red)-------
    
    ###########  AWAY  #########################################################
    htag = row['HTAG'] # Half Time Away Team Goals - HalfTimeGoals
    as_ = row['AS'] # Away Team Shots - Shots
    ast = row['AST'] # Away Team Shots on Target - ShotsOnTarget
    #ahw = row['AHW'] # Away Team Hit Woodwork----------------------------------
    ac = row['AC'] # Away Team Corners - Corners
    af = row['AF'] # Away Team Fouls Committed - FoulsCommitted
    #afkc = row['AFKC'] # Away Team Free Kicks Conceded-------------------------
    #ao = row['AO'] # Away Team Offsides ---------------------------------------
    ay = row['AY'] # Away Team Yellow Cards -         YellowCards
    ar = row['AR'] # Away Team Red Cards -            RedCards
    #abp = row['ABP'] # Away Team Bookings Points (10 = yellow, 25 = red)-------


    # Crear la primera fila para el equipo local
    row_local = pd.DataFrame({
          'MatchID': [match_id], 'Date': [date], 'Team': [home_team], 'Goals': [home_goals], 'TeamLocation': "Local", 'OpposingTeam': [away_team], 'FullTimeResult': [fullTimeResultHome], 'HalfTimeResult': [halfTimeResultHome],   
          'HalfTimeGoals': [hthg], 'ShotsOnTarget': [hst], 'Corners': [hc], 'FoulsCommitted': [hf], 'YellowCards': [hy], 'RedCards': [hr], 'Season': numeroTemporada
          })
    
    # Crear la segunda fila para el equipo visitante
    row_visitor = pd.DataFrame({
          'MatchID': [match_id], 'Date': [date], 'Team': [away_team], 'Goals': [away_goals], 'TeamLocation': "Visitante", 'OpposingTeam': [home_team], 'FullTimeResult': [fullTimeResultAway], 'HalfTimeResult': [halfTimeResultAway],   
          'HalfTimeGoals': [htag], 'ShotsOnTarget': [ast], 'Corners': [ac], 'FoulsCommitted': [af], 'YellowCards': [ay], 'RedCards': [ar], 'Season': numeroTemporada
          })
    
    # Concatenar las filas al DataFrame df_transformed
    df_transformed = pd.concat([df_transformed, row_local, row_visitor], ignore_index=True)

# Convertir las columnas 'MatchID' y 'Goals' a tipo numérico
df_transformed['MatchID'] = pd.to_numeric(df_transformed['MatchID'])
df_transformed['Goals'] = pd.to_numeric(df_transformed['Goals'])

In [917]:
# Imprimir el nuevo DataFrame df_transformed
print(df_transformed)

     MatchID        Date         Team  Goals TeamLocation OpposingTeam  \
0          1  16/08/2019   Ath Bilbao      1        Local    Barcelona
1          1  16/08/2019    Barcelona      0    Visitante   Ath Bilbao
2          2  17/08/2019        Celta      1        Local  Real Madrid
3          2  17/08/2019  Real Madrid      3    Visitante        Celta
4          3  17/08/2019     Valencia      1        Local     Sociedad
..       ...         ...          ...    ...          ...          ...
755      378  19/07/2020       Getafe      0    Visitante      Levante
756      379  19/07/2020      Osasuna      2        Local     Mallorca
757      379  19/07/2020     Mallorca      2    Visitante      Osasuna
758      380  19/07/2020      Sevilla      1        Local     Valencia
759      380  19/07/2020     Valencia      0    Visitante      Sevilla

    FullTimeResult HalfTimeResult HalfTimeGoals ShotsOnTarget Corners  \
0         Victoria         Empate             0             5       3
1          Derrota         Empate             0             2       8
2          Derrota        Derrota             0             4       6
3         Victoria       Victoria             1            11       4
4           Empate         Empate             0             6       3
..             ...            ...           ...           ...     ...
755        Derrota         Empate             0             4       8
756         Empate         Empate             1             5       3
757         Empate         Empate             1             4       5
758       Victoria         Empate             0             4       4
759        Derrota         Empate             0             2       7

    FoulsCommitted YellowCards RedCards Season
0               14           1        0  19-20
1                9           1        0  19-20
2               17           5        0  19-20
3               12           2        1  19-20
4               13           4        1  19-20
..             ...         ...      ...    ...
755             12           4        0  19-20
756             17           2        0  19-20
757             10           0        0  19-20
758             11           0        0  19-20
759              6           1        0  19-20

[760 rows x 15 columns]

In [918]:
df_transformed

,MatchID,Date,Team,Goals,TeamLocation,OpposingTeam,FullTimeResult,HalfTimeResult,HalfTimeGoals,ShotsOnTarget,Corners,FoulsCommitted,YellowCards,RedCards,Season
0,1,16/08/2019,Ath Bilbao,1,Local,Barcelona,Victoria,Empate,0,5,3,14,1,0,19-20
1,1,16/08/2019,Barcelona,0,Visitante,Ath Bilbao,Derrota,Empate,0,2,8,9,1,0,19-20
2,2,17/08/2019,Celta,1,Local,Real Madrid,Derrota,Derrota,0,4,6,17,5,0,19-20
3,2,17/08/2019,Real Madrid,3,Visitante,Celta,Victoria,Victoria,1,11,4,12,2,1,19-20
4,3,17/08/2019,Valencia,1,Local,Sociedad,Empate,Empate,0,6,3,13,4,1,19-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,378,19/07/2020,Getafe,0,Visitante,Levante,Derrota,Empate,0,4,8,12,4,0,19-20
756,379,19/07/2020,Osasuna,2,Local,Mallorca,Empate,Empate,1,5,3,17,2,0,19-20
757,379,19/07/2020,Mallorca,2,Visitante,Osasuna,Empate,Empate,1,4,5,10,0,0,19-20
758,380,19/07/2020,Sevilla,1,Local,Valencia,Victoria,Empate,0,4,4,11,0,0,19-20
759,380,19/07/2020,Valencia,0,Visitante,Sevilla,Derrota,Empate,0,2,7,6,1,0,19-20

### CSV PARTIDOS DEGLOSADO

In [919]:
nombre_csv = 'partidos_desglosados' + numeroTemporada + '.csv'

In [920]:
nombre_csv

'partidos_desglosados19-20.csv'

In [921]:
df_transformed.to_csv(nombre_csv, index=False)

### CSV ENCUENTROS

In [922]:
df

,MatchID,Season,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,1,19-20,SP1,16/08/2019,20:00,Ath Bilbao,Barcelona,1,0,H,...,1.97,0.75,1.93,2.00,1.91,2.01,2.02,2.03,1.91,1.98
1,2,19-20,SP1,17/08/2019,16:00,Celta,Real Madrid,1,3,A,...,2.63,1.00,1.82,1.97,1.85,2.07,2.00,2.20,1.82,2.06
2,3,19-20,SP1,17/08/2019,18:00,Valencia,Sociedad,1,1,D,...,1.82,-0.75,1.94,1.99,1.92,2.00,1.96,2.12,1.89,2.00
3,4,19-20,SP1,17/08/2019,19:00,Mallorca,Eibar,2,1,H,...,1.66,0.00,2.11,1.82,2.09,1.83,2.12,1.88,2.07,1.83
4,5,19-20,SP1,17/08/2019,20:00,Leganes,Osasuna,0,1,A,...,1.46,-0.50,1.89,2.04,1.90,2.01,1.95,2.06,1.90,1.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,376,19-20,SP1,19/07/2020,20:00,Granada,Ath Bilbao,4,0,H,...,1.78,-0.75,1.96,1.97,1.93,1.98,2.04,1.99,1.93,1.94
376,377,19-20,SP1,19/07/2020,20:00,Leganes,Real Madrid,2,2,D,...,2.06,0.25,2.03,1.90,2.05,1.87,2.06,1.93,2.00,1.88
377,378,19-20,SP1,19/07/2020,20:00,Levante,Getafe,1,0,H,...,2.17,1.25,1.88,2.05,1.86,2.05,1.91,2.08,1.86,2.01
378,379,19-20,SP1,19/07/2020,20:00,Osasuna,Mallorca,2,2,D,...,2.30,-0.75,1.85,2.08,1.85,2.07,1.89,2.11,1.84,2.04
379,380,19-20,SP1,19/07/2020,20:00,Sevilla,Valencia,1,0,H,...,2.35,-0.75,1.94,1.99,1.93,1.99,1.96,2.00,1.92,1.95

In [923]:
nombre_csv_encuentros = 'encuentros' + numeroTemporada + '.csv'

In [924]:
nombre_csv_encuentros

'encuentros19-20.csv'

In [925]:
df.to_csv(nombre_csv_encuentros, index=False)